# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Reckoning Risk
email: tom@reckoningrisk.com
description: >- # this means to ignore newlines until "baseurl:"
  A risk and science blog by young risk scientists
baseurl: "" # the subpath of your site, e.g. /blog
url: https://reckoningrisk.com  # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: TomMLogan
# github_username:  tommlogan
# linkedin_username: tom-logan-4b262a5b/
# scholar_username: NqnK14EAAAAJ
image: assets/img/og.jpg
image-height: 630px
image-width: 1200px
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
# source: /_jekyll
# destination: /blogs
permalink: /:title/
markdown: kramdown
highlighter: rouge

# Plugins
paginate: 5
paginate_path: "/:num/"
exclude:
  - '*.ini'
